name: Build Modern Null Launcher

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Java 17
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make starter stick
      run: gradle wrapper

    - name: Set permission
      run: chmod +x gradlew

    - name: Build 64-bit APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Save finished APK
      uses: actions/upload-artifact@v4.4.3
      with:
        name: NullLauncher-Modern
        path: "**/build/outputs/apk/**/*.apk"
